// Healthcare industry-specific catalog.

import type { RiskCatalogEntry, ConflictCatalogEntry } from "../types";

export const healthcareRisks: RiskCatalogEntry[] = [
  {
    id: "healthcare_privacy_breach",
    title: "Patient Data Privacy Breach",
    description: "PHI (Protected Health Information) is exposed due to inadequate security, causing regulatory fines and reputational damage.",
    industry: "Healthcare",
    category: "regulatory" as const,
    probability: "medium" as const,
    impact: "critical" as const,
    urgency: "critical" as const,
    phase: ["Planning", "Execution", "Monitoring", "Closing"],
    responseOptions: [
      {
        id: "privacy_1",
        title: "HIPAA compliance audit",
        description: "Conduct independent audit of security controls and PHI handling.",
        effectiveness: "mitigate" as const,
        estimatedCost: "high" as const,
      },
      {
        id: "privacy_2",
        title: "Encryption and access controls",
        description: "Implement end-to-end encryption and role-based access controls.",
        effectiveness: "avoid" as const,
        estimatedCost: "high" as const,
      },
    ],
    recommendedConsiderations: [
      "Establish data classification policy.",
      "Implement multi-factor authentication.",
      "Regular security awareness training.",
      "Incident response plan for breaches.",
    ],
    immediateMetricEffects: { quality: -50, satisfaction: -60 },
    pmbokDomain: "Risk Management",
    pmbokPrinciple: "Focus on quality",
    ecoDomain: "Business Environment" as const,
    masteryTopics: ["Process — Risk Management", "Process — Compliance"],
  },
  {
    id: "healthcare_workflow_disruption",
    title: "Clinical Workflow Disruption",
    description: "New system disrupts clinical workflow, reducing staff efficiency and impacting patient care delivery.",
    industry: "Healthcare",
    category: "external" as const,
    probability: "high" as const,
    impact: "high" as const,
    urgency: "critical" as const,
    phase: ["Execution", "Monitoring"],
    responseOptions: [
      {
        id: "workflow_1",
        title: "Clinical user testing",
        description: "Involve clinical staff in UAT to surface workflow issues early.",
        effectiveness: "mitigate" as const,
        estimatedCost: "high" as const,
      },
      {
        id: "workflow_2",
        title: "Phased rollout",
        description: "Roll out in phases by department with clinical support.",
        effectiveness: "mitigate" as const,
        estimatedCost: "high" as const,
      },
    ],
    recommendedConsiderations: [
      "Include clinical leaders in design.",
      "Train staff before go-live.",
      "Have fallback manual processes.",
      "24/7 support during rollout.",
    ],
    immediateMetricEffects: { satisfaction: -30, morale: -20 },
    delayedEffects: [
      {
        trigger: "System used in production without optimization",
        daysDelay: 7,
        metricEffects: { satisfaction: -40, quality: -25 },
      },
    ],
    pmbokDomain: "Quality Management",
    pmbokPrinciple: "Focus on quality",
    ecoDomain: "Business Environment" as const,
    masteryTopics: ["Process — Change Management", "People — Stakeholder Engagement"],
  },
  {
    id: "healthcare_regulatory_approval_delay",
    title: "Regulatory Approval Delay",
    description: "FDA or other regulatory approval takes longer than planned, delaying market entry or implementation.",
    industry: "Healthcare",
    category: "regulatory" as const,
    probability: "medium" as const,
    impact: "high" as const,
    urgency: "high" as const,
    phase: ["Planning", "Execution"],
    responseOptions: [
      {
        id: "regulatory_1",
        title: "Early FDA engagement",
        description: "Have pre-submission meetings with FDA to clarify requirements.",
        effectiveness: "mitigate" as const,
        estimatedCost: "medium" as const,
      },
      {
        id: "regulatory_2",
        title: "Buffer timeline",
        description: "Add regulatory buffer to project schedule.",
        effectiveness: "accept" as const,
        estimatedCost: "low" as const,
      },
    ],
    recommendedConsiderations: [
      "Engage regulatory specialists early.",
      "Document compliance requirements.",
      "Plan parallel activities where possible.",
    ],
    immediateMetricEffects: { schedule: -30 },
    pmbokDomain: "Schedule Management",
    pmbokPrinciple: "Steer the project",
    ecoDomain: "Business Environment" as const,
    masteryTopics: ["Process — Compliance"],
  },
  {
    id: "healthcare_vendor_interop",
    title: "Vendor Interoperability Failure",
    description: "EHR system does not interoperate with existing vendor systems (labs, imaging, pharmacy), creating data silos.",
    industry: "Healthcare",
    category: "technical" as const,
    probability: "medium" as const,
    impact: "high" as const,
    urgency: "high" as const,
    phase: ["Planning", "Execution"],
    responseOptions: [
      {
        id: "interop_1",
        title: "FHIR/HL7 validation",
        description: "Validate vendor systems support standard healthcare data exchange protocols.",
        effectiveness: "mitigate" as const,
        estimatedCost: "high" as const,
      },
      {
        id: "interop_2",
        title: "Custom integration",
        description: "Build custom integration layer if standard protocols not supported.",
        effectiveness: "mitigate" as const,
        estimatedCost: "high" as const,
      },
    ],
    recommendedConsiderations: [
      "Establish interoperability requirements upfront.",
      "Use industry standards (FHIR, HL7).",
      "Include vendor IT in design.",
    ],
    immediateMetricEffects: { quality: -25 },
    pmbokDomain: "Scope Management",
    pmbokPrinciple: "Focus on quality",
    ecoDomain: "Process" as const,
    masteryTopics: ["Process — Integration"],
  },
  {
    id: "healthcare_user_adoption_resist",
    title: "User Adoption Resistance",
    description: "Clinical staff resist using new system, continuing with workarounds and legacy processes.",
    industry: "Healthcare",
    category: "organizational" as const,
    probability: "high" as const,
    impact: "high" as const,
    urgency: "high" as const,
    phase: ["Execution", "Monitoring"],
    responseOptions: [
      {
        id: "adopt_1",
        title: "Change management program",
        description: "Establish dedicated change management team with clinical champions.",
        effectiveness: "mitigate" as const,
        estimatedCost: "medium" as const,
      },
      {
        id: "adopt_2",
        title: "User-centered design",
        description: "Involve end users in design to ensure usability.",
        effectiveness: "mitigate" as const,
        estimatedCost: "high" as const,
      },
    ],
    recommendedConsiderations: [
      "Identify clinical champions early.",
      "Provide extensive training.",
      "Listen to staff concerns.",
      "Celebrate early wins.",
    ],
    immediateMetricEffects: { satisfaction: -25, morale: -15 },
    pmbokDomain: "Change Management",
    pmbokPrinciple: "Manage stakeholder engagement",
    ecoDomain: "People" as const,
    masteryTopics: ["People — Change Management", "People — Stakeholder Engagement"],
  },
];

export const healthcareConflicts: ConflictCatalogEntry[] = [
  {
    id: "healthcare_clinical_vs_it",
    title: "Clinical Leadership vs. IT Leadership",
    description: "Clinical leaders want simplicity and quick implementation; IT wants security, compliance, and technical rigor.",
    industry: "Healthcare",
    conflictType: "stakeholder" as const,
    parties: ["Chief Medical Officer", "CIO", "Chief Nursing Officer"],
    rootCause: "Different priorities and risk tolerance for clinical vs. technical concerns.",
    phase: ["Planning", "Execution"],
    availableTechniques: [
      {
        id: "tech_1",
        name: "Shared governance model",
        description: "Establish joint clinical-IT governance with equal representation.",
        effectiveness: "excellent" as const,
        timeToResolve: "weeks" as const,
      },
      {
        id: "tech_2",
        name: "Executive alignment",
        description: "Engage CEO/COO to align organizational priorities.",
        effectiveness: "good" as const,
        timeToResolve: "days" as const,
      },
    ],
    likelyConsequences: [
      "Slow decision-making",
      "Compromised system design",
      "Implementation delays",
    ],
    immediateMetricEffects: { morale: -10, schedule: -10 },
    pmbokDomain: "Stakeholder Management",
    pmbokPrinciple: "Manage stakeholder engagement",
    ecoDomain: "People" as const,
    masteryTopics: ["People — Conflict Resolution", "People — Stakeholder Engagement"],
  },
  {
    id: "healthcare_safety_vs_schedule",
    title: "Patient Safety vs. Schedule Pressure",
    description: "Pressure to meet timeline conflicts with need to ensure patient safety through rigorous testing and validation.",
    industry: "Healthcare",
    conflictType: "values" as const,
    parties: ["Clinical Director", "Project Sponsor", "Quality Officer"],
    rootCause: "Business pressure vs. clinical safety imperative.",
    phase: ["Execution", "Monitoring"],
    availableTechniques: [
      {
        id: "tech_1",
        name: "Safety-critical milestones",
        description: "Define non-negotiable safety milestones that cannot be compressed.",
        effectiveness: "excellent" as const,
        timeToResolve: "days" as const,
      },
      {
        id: "tech_2",
        name: "Parallel testing tracks",
        description: "Run UAT and system testing in parallel where possible.",
        effectiveness: "good" as const,
        timeToResolve: "weeks" as const,
      },
    ],
    likelyConsequences: [
      "Post-launch patient safety incidents",
      "Regulatory investigation",
      "Reputational damage",
    ],
    immediateMetricEffects: { quality: -20 },
    pmbokDomain: "Quality Management",
    pmbokPrinciple: "Focus on quality",
    ecoDomain: "Business Environment" as const,
    masteryTopics: ["Process — Quality Management", "People — Conflict Resolution"],
  },
  {
    id: "healthcare_compliance_vs_usability",
    title: "Compliance vs. Usability",
    description: "Need for HIPAA compliance and audit trails creates complex workflows that reduce clinical usability.",
    industry: "Healthcare",
    conflictType: "process" as const,
    parties: ["Compliance Officer", "UX Designer", "Chief Medical Officer"],
    rootCause: "Regulatory requirements vs. user experience goals.",
    phase: ["Planning", "Execution"],
    availableTechniques: [
      {
        id: "tech_1",
        name: "Privacy by design",
        description: "Integrate compliance into design from the start, not as an afterthought.",
        effectiveness: "excellent" as const,
        timeToResolve: "weeks" as const,
      },
    ],
    likelyConsequences: [
      "Poor system adoption",
      "Clinical workarounds",
      "Compliance gaps",
    ],
    immediateMetricEffects: { morale: -15, satisfaction: -10 },
    pmbokDomain: "Quality Management",
    pmbokPrinciple: "Focus on quality",
    ecoDomain: "Business Environment" as const,
    masteryTopics: ["Process — Design"],
  },
];
