// Software / SaaS industry-specific catalog.

import type { RiskCatalogEntry, ConflictCatalogEntry } from "../types";

export const softwareRisks: RiskCatalogEntry[] = [
  {
    id: "software_integration_dep",
    title: "Critical Integration Dependency",
    description: "Project depends on third-party API or service that is unstable, under-documented, or subject to breaking changes.",
    industry: "Software",
    category: "technical" as const,
    probability: "high" as const,
    impact: "critical" as const,
    urgency: "high" as const,
    phase: ["Planning", "Execution", "Monitoring"],
    responseOptions: [
      {
        id: "integration_1",
        title: "API contract testing",
        description: "Implement contract tests to catch breaking changes early.",
        effectiveness: "mitigate" as const,
        estimatedCost: "medium" as const,
      },
      {
        id: "integration_2",
        title: "Abstraction layer",
        description: "Create an adapter pattern to decouple from the external service.",
        effectiveness: "mitigate" as const,
        estimatedCost: "high" as const,
      },
      {
        id: "integration_3",
        title: "Build alternative",
        description: "Develop fallback or alternative integration path.",
        effectiveness: "avoid" as const,
        estimatedCost: "high" as const,
      },
    ],
    recommendedConsiderations: [
      "Establish SLA monitoring for the dependency.",
      "Document integration points and failure modes.",
      "Negotiate support agreements with vendor.",
      "Run chaos engineering tests.",
    ],
    immediateMetricEffects: { quality: -20, schedule: -10 },
    delayedEffects: [
      {
        trigger: "Integration point fails in production",
        daysDelay: 1,
        metricEffects: { quality: -30, satisfaction: -25 },
      },
    ],
    pmbokDomain: "Risk Management",
    pmbokPrinciple: "Focus on quality",
    ecoDomain: "Process" as const,
    masteryTopics: ["Process — Risk Management", "Technical — Integration"],
  },
  {
    id: "software_security_vuln",
    title: "Security Vulnerability Discovery",
    description: "Critical security vulnerability discovered late in development or after production deployment.",
    industry: "Software",
    category: "quality" as const,
    probability: "medium" as const,
    impact: "critical" as const,
    urgency: "critical" as const,
    phase: ["Execution", "Monitoring", "Closing"],
    responseOptions: [
      {
        id: "security_1",
        title: "Security review early",
        description: "Conduct threat modeling and security reviews during design.",
        effectiveness: "avoid" as const,
        estimatedCost: "high" as const,
      },
      {
        id: "security_2",
        title: "Penetration testing",
        description: "Contract professional penetration testing before release.",
        effectiveness: "mitigate" as const,
        estimatedCost: "high" as const,
      },
    ],
    recommendedConsiderations: [
      "Establish security SDLC practices.",
      "Use OWASP guidelines.",
      "Implement automated security scanning in CI/CD.",
      "Create incident response plan.",
    ],
    immediateMetricEffects: { quality: -40, satisfaction: -50 },
    pmbokDomain: "Quality Management",
    pmbokPrinciple: "Focus on quality",
    ecoDomain: "Process" as const,
    masteryTopics: ["Process — Quality Management", "Process — Risk Management"],
  },
  {
    id: "software_unstable_requirements",
    title: "Unstable or Ambiguous Requirements",
    description: "Requirements change frequently or are poorly defined, leading to rework and delays.",
    industry: "Software",
    category: "scope" as const,
    probability: "high" as const,
    impact: "high" as const,
    urgency: "high" as const,
    phase: ["Initiation", "Planning", "Execution"],
    responseOptions: [
      {
        id: "req_1",
        title: "Spike or prototype",
        description: "Build a quick prototype to clarify requirements with stakeholders.",
        effectiveness: "mitigate" as const,
        estimatedCost: "medium" as const,
      },
      {
        id: "req_2",
        title: "Agile approach with feedback loops",
        description: "Use iterative development with frequent stakeholder review.",
        effectiveness: "mitigate" as const,
        estimatedCost: "low" as const,
      },
    ],
    recommendedConsiderations: [
      "Engage product owner early and often.",
      "Document requirements in acceptance criteria.",
      "Use user stories and BDD.",
      "Establish definition of done.",
    ],
    immediateMetricEffects: { scope_integrity: -15 },
    pmbokDomain: "Scope Management",
    pmbokPrinciple: "Steer the project",
    ecoDomain: "Process" as const,
    masteryTopics: ["Process — Scope Management"],
  },
  {
    id: "software_cloud_cost_overrun",
    title: "Cloud Cost Overrun",
    description: "Unexpected cloud infrastructure or licensing costs exceed budget due to resource inefficiency or scale.",
    industry: "Software",
    category: "budget" as const,
    probability: "medium" as const,
    impact: "high" as const,
    urgency: "high" as const,
    phase: ["Execution", "Monitoring"],
    responseOptions: [
      {
        id: "cost_1",
        title: "Cost monitoring and optimization",
        description: "Implement cloud cost monitoring with alerts and optimization recommendations.",
        effectiveness: "mitigate" as const,
        estimatedCost: "low" as const,
      },
      {
        id: "cost_2",
        title: "Reserved instances and commitments",
        description: "Purchase reserved instances or cloud commitments for cost savings.",
        effectiveness: "mitigate" as const,
        estimatedCost: "low" as const,
      },
    ],
    recommendedConsiderations: [
      "Establish cloud cost budget.",
      "Implement tagging strategy.",
      "Regular cost reviews.",
      "Right-size resources.",
    ],
    immediateMetricEffects: { budget: -20 },
    pmbokDomain: "Cost Management",
    pmbokPrinciple: "Steer the project",
    ecoDomain: "Business Environment" as const,
    masteryTopics: ["Process — Cost Management"],
  },
  {
    id: "software_key_person_risk",
    title: "Key Engineer Departure",
    description: "Critical engineer leaves the project, taking important knowledge about architecture or business logic.",
    industry: "Software",
    category: "resource" as const,
    probability: "medium" as const,
    impact: "high" as const,
    urgency: "high" as const,
    phase: ["Execution", "Monitoring"],
    responseOptions: [
      {
        id: "person_1",
        title: "Knowledge transfer and documentation",
        description: "Have departing engineer document critical systems and mentor replacement.",
        effectiveness: "mitigate" as const,
        estimatedCost: "medium" as const,
      },
      {
        id: "person_2",
        title: "Pair programming culture",
        description: "Establish pair programming to distribute knowledge across team.",
        effectiveness: "mitigate" as const,
        estimatedCost: "medium" as const,
      },
    ],
    recommendedConsiderations: [
      "Keep team engaged and challenged.",
      "Foster mentoring culture.",
      "Document architecture decisions.",
      "Maintain competitive compensation.",
    ],
    immediateMetricEffects: { productivity: -30, morale: -10 },
    delayedEffects: [
      {
        trigger: "Replacement engineer ramping up",
        daysDelay: 14,
        metricEffects: { schedule: -20, quality: -10 },
      },
    ],
    pmbokDomain: "Resource Management",
    pmbokPrinciple: "Manage stakeholder engagement",
    ecoDomain: "People" as const,
    masteryTopics: ["People — Resource Planning", "People — Team Development"],
  },
];

export const softwareConflicts: ConflictCatalogEntry[] = [
  {
    id: "software_product_vs_eng",
    title: "Product vs. Engineering Scope Dispute",
    description: "Product wants maximum features and fast delivery; Engineering wants time for architecture and quality.",
    industry: "Software",
    conflictType: "stakeholder" as const,
    parties: ["Product Manager", "Engineering Lead", "Architect"],
    rootCause: "Different incentives and timescales for success.",
    phase: ["Planning", "Execution"],
    availableTechniques: [
      {
        id: "tech_1",
        name: "Roadmap alignment",
        description: "Co-create a product roadmap with both product and engineering input.",
        effectiveness: "good" as const,
        timeToResolve: "weeks" as const,
      },
      {
        id: "tech_2",
        name: "Technical roadmap",
        description: "Create a parallel technical debt roadmap that Product understands.",
        effectiveness: "excellent" as const,
        timeToResolve: "weeks" as const,
      },
    ],
    likelyConsequences: [
      "Accumulation of technical debt",
      "Engineering team frustration",
      "Quality and reliability issues",
      "Turnover in engineering",
    ],
    immediateMetricEffects: { morale: -15, quality: -10 },
    pmbokDomain: "Scope Management",
    pmbokPrinciple: "Steer the project",
    ecoDomain: "People" as const,
    masteryTopics: ["People — Conflict Resolution", "Process — Scope Management"],
  },
  {
    id: "software_agile_vs_governance",
    title: "Agile Team vs. Governance Conflict",
    description: "Agile team wants autonomy and flexibility; Corporate governance wants compliance and documentation.",
    industry: "Software",
    conflictType: "process" as const,
    parties: ["Scrum Master", "PMO", "Compliance Officer"],
    rootCause: "Different process philosophies and risk tolerance.",
    phase: ["Execution"],
    availableTechniques: [
      {
        id: "tech_1",
        name: "Disciplined Agile (DAD)",
        description: "Adopt a hybrid approach that balances agility with governance.",
        effectiveness: "excellent" as const,
        timeToResolve: "weeks" as const,
      },
      {
        id: "tech_2",
        name: "Governance checkpoints",
        description: "Define lightweight governance touchpoints without blocking sprints.",
        effectiveness: "good" as const,
        timeToResolve: "days" as const,
      },
    ],
    likelyConsequences: [
      "Team frustration with process overhead",
      "Slow decision-making",
      "Reduced agility",
    ],
    immediateMetricEffects: { morale: -10, schedule: -5 },
    pmbokDomain: "Process Improvement",
    pmbokPrinciple: "Tailor to context",
    ecoDomain: "Process" as const,
    masteryTopics: ["Process — Process Improvement"],
  },
  {
    id: "software_technical_debt_pressure",
    title: "Technical Debt vs. Release Pressure",
    description: "Pressure to release quickly conflicts with need to address technical debt and maintain code quality.",
    industry: "Software",
    conflictType: "values" as const,
    parties: ["Product Manager", "Engineering Lead", "Release Manager"],
    rootCause: "Business pressure vs. long-term engineering health.",
    phase: ["Execution", "Monitoring"],
    availableTechniques: [
      {
        id: "tech_1",
        name: "Allocate sprint capacity",
        description: "Reserve 20-30% of sprint for technical work.",
        effectiveness: "good" as const,
        timeToResolve: "days" as const,
      },
      {
        id: "tech_2",
        name: "Define quality standards",
        description: "Establish non-negotiable quality thresholds before release.",
        effectiveness: "excellent" as const,
        timeToResolve: "days" as const,
      },
    ],
    likelyConsequences: [
      "Production incidents and outages",
      "Decreased velocity over time",
      "Staff burnout",
    ],
    immediateMetricEffects: { quality: -20 },
    delayedEffects: [
      {
        trigger: "3+ sprints with < 10% technical work",
        daysDelay: 21,
        metricEffects: { schedule: -30, quality: -20 },
      },
    ],
    pmbokDomain: "Quality Management",
    pmbokPrinciple: "Focus on quality",
    ecoDomain: "Process" as const,
    masteryTopics: ["Process — Quality Management"],
  },
];
