import type { Scenario } from "./types";

export const PHASE_ORDER = [
  "initiation",
  "planning",
  "execution",
  "monitoring",
  "closing",
] as const;

export const PHASE_META: Record<
  (typeof PHASE_ORDER)[number],
  { label: string; blurb: string }
> = {
  initiation: { label: "Initiation", blurb: "Charter, business case, stakeholders" },
  planning: { label: "Planning", blurb: "WBS, schedule, budget, risk & comms" },
  execution: { label: "Execution", blurb: "Team, vendors, deliverables" },
  monitoring: { label: "Monitoring & Control", blurb: "Performance, changes, issues" },
  closing: { label: "Closing", blurb: "Delivery, lessons learned, evaluation" },
};

// Phase scenarios: exactly the "milestone" decisions per phase.
export const PHASE_SCENARIOS: Scenario[] = [
  {
    id: "init-1",
    phase: "initiation",
    kind: "phase",
    title: "Draft the Project Charter",
    body: "The sponsor wants the charter today. High-level scope is fuzzy and no stakeholder register exists yet. What do you do?",
    choices: [
      {
        id: "a",
        label: "Draft charter with sponsor + run rapid stakeholder identification in parallel",
        rationale: "Balances speed with PMBOK 6 Identify Stakeholders and Develop Charter integration.",
        impact: { stakeholders: 5, risk: -5, scope: 5 },
        xp: 25,
        quality: "excellent",
      },
      {
        id: "b",
        label: "Sign off a placeholder charter now and fix later",
        rationale: "Skips Integration Management foundations; scope and risk creep in.",
        impact: { scope: -15, risk: 15, stakeholders: -5 },
        xp: 5,
        quality: "poor",
      },
      {
        id: "c",
        label: "Delay the charter until full requirements are collected",
        rationale: "Confuses Initiating with Planning; sponsor loses confidence.",
        impact: { stakeholders: -10, schedule: -10 },
        xp: 8,
        quality: "risky",
      },
      {
        id: "d",
        label: "Charter with clear success criteria + assumptions/constraints logged",
        rationale: "Solid PMBOK 7 stewardship + tailoring; explicit assumptions reduce future risk.",
        impact: { scope: 8, risk: -8, stakeholders: 5 },
        xp: 22,
        quality: "excellent",
      },
    ],
  },
  {
    id: "plan-1",
    phase: "planning",
    kind: "phase",
    title: "Build the Schedule & Risk Plan",
    body: "You have a target date from the sponsor but the team estimates 20% more effort. How do you plan?",
    choices: [
      {
        id: "a",
        label: "Force team estimates down to hit the date",
        rationale: "Ignores realistic estimating; morale and quality collapse.",
        impact: { schedule: 10, morale: -20, risk: 20, scope: -10 },
        xp: 3,
        quality: "poor",
      },
      {
        id: "b",
        label: "Negotiate scope reduction + reserve analysis + risk register",
        rationale: "Classic PMBOK: scope/schedule/cost trade + management reserves.",
        impact: { scope: 5, risk: -15, stakeholders: 5, morale: 5 },
        xp: 25,
        quality: "excellent",
      },
      {
        id: "c",
        label: "Add contractors to compress the schedule",
        rationale: "Crashing works but adds cost and coordination risk.",
        impact: { budget: -10, schedule: 5, risk: 5 },
        xp: 15,
        quality: "good",
      },
      {
        id: "d",
        label: "Commit to date, hide the gap in the plan",
        rationale: "Violates transparency principle; catastrophic in Monitoring.",
        impact: { risk: 25, stakeholders: -10, morale: -10 },
        xp: 0,
        quality: "poor",
      },
    ],
  },
  {
    id: "exec-1",
    phase: "execution",
    kind: "phase",
    title: "Kick Off Execution",
    body: "Team is assembled, vendor onboarded. First sprint/deliverable starts Monday. Where do you invest your first week?",
    choices: [
      {
        id: "a",
        label: "Working agreements, definition of done, comms cadence with stakeholders",
        rationale: "Hybrid best practice: team charter + PMBOK Manage Communications.",
        impact: { morale: 12, stakeholders: 8, risk: -5 },
        xp: 22,
        quality: "excellent",
      },
      {
        id: "b",
        label: "Jump straight into building — velocity matters",
        rationale: "Skipping team norms drives rework and conflict.",
        impact: { morale: -8, risk: 10, scope: -5 },
        xp: 5,
        quality: "poor",
      },
      {
        id: "c",
        label: "Detailed micromanagement of every task",
        rationale: "Violates servant leadership; morale drops.",
        impact: { morale: -15, schedule: 3 },
        xp: 6,
        quality: "risky",
      },
      {
        id: "d",
        label: "Run a risk workshop with the team & vendor",
        rationale: "Good but incomplete without team norms; still valuable.",
        impact: { risk: -12, stakeholders: 3 },
        xp: 16,
        quality: "good",
      },
    ],
  },
  {
    id: "mon-1",
    phase: "monitoring",
    kind: "phase",
    title: "Mid-Project Health Check",
    body: "EVM shows CPI 0.88 and SPI 0.92. Sponsor asks for status. How do you respond?",
    choices: [
      {
        id: "a",
        label: "Transparent report + variance analysis + corrective action plan",
        rationale: "Perform Integrated Change Control + Control Costs done right.",
        impact: { stakeholders: 10, risk: -10, budget: -3 },
        xp: 25,
        quality: "excellent",
      },
      {
        id: "b",
        label: "Report 'green' — you'll recover next month",
        rationale: "Status manipulation destroys trust when reality hits.",
        impact: { stakeholders: -20, risk: 15 },
        xp: 0,
        quality: "poor",
      },
      {
        id: "c",
        label: "Escalate immediately, request more budget",
        rationale: "Correct escalation, but no corrective plan attached.",
        impact: { stakeholders: -3, budget: -10, risk: -5 },
        xp: 12,
        quality: "good",
      },
      {
        id: "d",
        label: "Cut scope silently to catch up",
        rationale: "Bypasses change control — the classic PMBOK anti-pattern.",
        impact: { scope: -20, stakeholders: -10 },
        xp: 3,
        quality: "poor",
      },
    ],
  },
  {
    id: "close-1",
    phase: "closing",
    kind: "phase",
    title: "Close the Project",
    body: "Final deliverable is accepted. What closes the project properly?",
    choices: [
      {
        id: "a",
        label: "Formal acceptance + lessons learned + release resources + archive",
        rationale: "Textbook Close Project or Phase.",
        impact: { stakeholders: 10, morale: 10 },
        xp: 25,
        quality: "excellent",
      },
      {
        id: "b",
        label: "Move team to next project immediately",
        rationale: "Skips knowledge transfer and closure ceremonies.",
        impact: { morale: -10, stakeholders: -5 },
        xp: 5,
        quality: "poor",
      },
      {
        id: "c",
        label: "Retrospective only, skip formal sign-off",
        rationale: "Missing contractual closure creates downstream disputes.",
        impact: { stakeholders: -10, risk: 10 },
        xp: 8,
        quality: "risky",
      },
      {
        id: "d",
        label: "Client handover + benefits realization plan + lessons learned",
        rationale: "PMBOK 7 outcome/value orientation.",
        impact: { stakeholders: 12, morale: 8 },
        xp: 24,
        quality: "excellent",
      },
    ],
  },
];

// Random events can fire between phase scenarios.
export const RANDOM_EVENTS: Scenario[] = [
  {
    id: "ev-scope",
    phase: "execution",
    kind: "event",
    title: "⚠️ Client requests a major scope change",
    body: "The client wants a new module added — no timeline or budget change. They insist it's 'small'.",
    choices: [
      {
        id: "a",
        label: "Log a change request, impact analysis, route through CCB",
        rationale: "Perform Integrated Change Control — the correct PMBOK response.",
        impact: { scope: 8, stakeholders: 5, risk: -5 },
        xp: 22,
        quality: "excellent",
      },
      {
        id: "b",
        label: "Say yes to keep the client happy",
        rationale: "Uncontrolled scope creep.",
        impact: { scope: -20, budget: -10, schedule: -10, risk: 15 },
        xp: 2,
        quality: "poor",
      },
      {
        id: "c",
        label: "Refuse outright — 'not in scope'",
        rationale: "Damages the stakeholder relationship without exploring options.",
        impact: { stakeholders: -15, scope: 3 },
        xp: 6,
        quality: "risky",
      },
    ],
  },
  {
    id: "ev-vendor",
    phase: "execution",
    kind: "event",
    title: "⚠️ Vendor announces a 3-week delay",
    body: "Your critical-path vendor slips 3 weeks. Contract has a late-delivery clause.",
    choices: [
      {
        id: "a",
        label: "Trigger risk response, invoke contract clause, re-plan critical path",
        rationale: "Risk response + procurement management done right.",
        impact: { risk: -8, schedule: -5, budget: 3 },
        xp: 22,
        quality: "excellent",
      },
      {
        id: "b",
        label: "Wait and hope they recover",
        rationale: "No response strategy = compound risk.",
        impact: { schedule: -20, risk: 20 },
        xp: 2,
        quality: "poor",
      },
      {
        id: "c",
        label: "Bring work in-house immediately",
        rationale: "Costly and burns morale, but reduces dependency.",
        impact: { budget: -15, morale: -8, schedule: -3, risk: -5 },
        xp: 12,
        quality: "good",
      },
    ],
  },
  {
    id: "ev-resign",
    phase: "execution",
    kind: "event",
    title: "⚠️ Key team member resigns",
    body: "Your lead engineer resigns with 2 weeks notice. They own 40% of the domain knowledge.",
    choices: [
      {
        id: "a",
        label: "Knowledge transfer plan + pair programming + update risk register",
        rationale: "Resource management + risk mitigation.",
        impact: { risk: -8, morale: -3, schedule: -3 },
        xp: 20,
        quality: "excellent",
      },
      {
        id: "b",
        label: "Backfill with a contractor next month",
        rationale: "Reasonable but delayed; knowledge is already walking out.",
        impact: { budget: -8, schedule: -8, risk: 5 },
        xp: 10,
        quality: "good",
      },
      {
        id: "c",
        label: "Ignore — the team will absorb it",
        rationale: "Guaranteed burnout and delivery risk.",
        impact: { morale: -15, risk: 20, schedule: -10 },
        xp: 2,
        quality: "poor",
      },
    ],
  },
  {
    id: "ev-budget",
    phase: "monitoring",
    kind: "event",
    title: "⚠️ Finance cuts your budget by 15%",
    body: "Corporate finance mandates a 15% budget cut across all projects.",
    choices: [
      {
        id: "a",
        label: "Re-baseline: negotiate scope with sponsor + update plans",
        rationale: "Change control + realistic re-planning.",
        impact: { scope: -8, stakeholders: 3, risk: -5, budget: -15 },
        xp: 22,
        quality: "excellent",
      },
      {
        id: "b",
        label: "Cut quality assurance to save money",
        rationale: "Manage Quality violation — defects will explode.",
        impact: { risk: 25, scope: -10, stakeholders: -10, budget: -15 },
        xp: 2,
        quality: "poor",
      },
      {
        id: "c",
        label: "Draw from management reserve, delay decision",
        rationale: "Buys time but doesn't address the mandate.",
        impact: { budget: -15, risk: 8 },
        xp: 10,
        quality: "risky",
      },
    ],
  },
  {
    id: "ev-reg",
    phase: "monitoring",
    kind: "event",
    title: "⚠️ New regulatory requirement drops",
    body: "A compliance rule goes live next quarter and affects your deliverable.",
    choices: [
      {
        id: "a",
        label: "Assess impact, log change request, engage compliance & sponsor",
        rationale: "Integrated Change Control + Stakeholder Engagement.",
        impact: { risk: -10, stakeholders: 5, scope: 3, budget: -5 },
        xp: 22,
        quality: "excellent",
      },
      {
        id: "b",
        label: "Ship current version, retrofit later",
        rationale: "Non-compliant delivery = project failure.",
        impact: { risk: 25, stakeholders: -15 },
        xp: 3,
        quality: "poor",
      },
      {
        id: "c",
        label: "Pause the project until requirements are clear",
        rationale: "Overreaction — you can plan under uncertainty.",
        impact: { schedule: -15, stakeholders: -5 },
        xp: 8,
        quality: "risky",
      },
    ],
  },
];
