// Global fallback catalog: industry-agnostic, universally applicable scenarios.

import type { RiskCatalogEntry, ConflictCatalogEntry } from "./types";

export const globalCatalog = {
  risks: [
    {
      id: "global_scope_creep",
      title: "Scope Creep",
      description: "Uncontrolled expansion of project scope beyond initial requirements, leading to budget and schedule overruns.",
      industry: "Global",
      category: "scope" as const,
      probability: "high" as const,
      impact: "high" as const,
      urgency: "high" as const,
      phase: ["Planning", "Execution", "Monitoring"],
      responseOptions: [
        {
          id: "scope_control_1",
          title: "Enforce change control",
          description: "Implement strict change-request process with impact analysis.",
          effectiveness: "mitigate" as const,
          estimatedCost: "medium" as const,
        },
        {
          id: "scope_control_2",
          title: "Freeze requirements",
          description: "Define a cutoff date after which no new requirements are accepted.",
          effectiveness: "avoid" as const,
          estimatedCost: "low" as const,
        },
      ],
      recommendedConsiderations: [
        "Establish a clear change-request process.",
        "Baseline the scope formally.",
        "Educate stakeholders on impact of changes.",
      ],
      immediateMetricEffects: { scope_integrity: -10 },
      pmbokDomain: "Scope Management",
      pmbokPrinciple: "Steer the project",
      ecoDomain: "Process" as const,
      masteryTopics: ["Process — Scope Management", "People — Stakeholder Engagement"],
    },
    {
      id: "global_resource_unavail",
      title: "Key Resource Unavailability",
      description: "Loss or unavailability of critical project team members due to illness, departure, or competing priorities.",
      industry: "Global",
      category: "resource" as const,
      probability: "medium" as const,
      impact: "high" as const,
      urgency: "high" as const,
      phase: ["Execution", "Monitoring"],
      responseOptions: [
        {
          id: "resource_1",
          title: "Cross-train backup resources",
          description: "Develop a backup person with key skills.",
          effectiveness: "mitigate" as const,
          estimatedCost: "high" as const,
        },
        {
          id: "resource_2",
          title: "Hire contract resources",
          description: "Bring in external contractors on short notice.",
          effectiveness: "mitigate" as const,
          estimatedCost: "high" as const,
        },
      ],
      recommendedConsiderations: [
        "Document critical knowledge.",
        "Identify single points of failure.",
        "Build relationships with contract vendors.",
      ],
      immediateMetricEffects: { schedule: -15, productivity: -20 },
      pmbokDomain: "Resource Management",
      pmbokPrinciple: "Manage stakeholder engagement",
      ecoDomain: "People" as const,
      masteryTopics: ["People — Resource Planning"],
    },
    {
      id: "global_stakeholder_misalign",
      title: "Stakeholder Misalignment",
      description: "Key stakeholders have conflicting priorities, expectations, or communication breakdowns.",
      industry: "Global",
      category: "organizational" as const,
      probability: "high" as const,
      impact: "medium" as const,
      urgency: "medium" as const,
      phase: ["Initiation", "Planning", "Execution"],
      responseOptions: [
        {
          id: "align_1",
          title: "Stakeholder alignment workshop",
          description: "Facilitate a meeting to surface and resolve conflicts.",
          effectiveness: "mitigate" as const,
          estimatedCost: "medium" as const,
        },
        {
          id: "align_2",
          title: "Executive sponsorship",
          description: "Escalate to executive sponsor to enforce alignment.",
          effectiveness: "mitigate" as const,
          estimatedCost: "low" as const,
        },
      ],
      recommendedConsiderations: [
        "Hold regular stakeholder forums.",
        "Document decisions and rationale.",
        "Maintain a RACI matrix.",
      ],
      immediateMetricEffects: { trust: -10, morale: -5 },
      pmbokDomain: "Stakeholder Management",
      pmbokPrinciple: "Manage stakeholder engagement",
      ecoDomain: "People" as const,
      masteryTopics: ["People — Stakeholder Engagement"],
    },
    {
      id: "global_tech_debt",
      title: "Technical Debt Accumulation",
      description: "Shortcuts taken during development create maintenance burden and quality issues.",
      industry: "Global",
      category: "quality" as const,
      probability: "medium" as const,
      impact: "high" as const,
      urgency: "medium" as const,
      phase: ["Execution", "Monitoring"],
      responseOptions: [
        {
          id: "debt_1",
          title: "Allocate sprint time for refactoring",
          description: "Reserve 20-30% of sprint capacity for quality work.",
          effectiveness: "mitigate" as const,
          estimatedCost: "medium" as const,
        },
        {
          id: "debt_2",
          title: "Code review standards",
          description: "Enforce code review and quality gates.",
          effectiveness: "avoid" as const,
          estimatedCost: "low" as const,
        },
      ],
      recommendedConsiderations: [
        "Track technical debt in backlog.",
        "Define quality thresholds.",
        "Regular architecture reviews.",
      ],
      immediateMetricEffects: { quality: -8 },
      delayedEffects: [
        {
          trigger: "3 sprints without refactoring",
          daysDelay: 21,
          metricEffects: { quality: -15, schedule: -20 },
        },
      ],
      pmbokDomain: "Quality Management",
      pmbokPrinciple: "Focus on quality",
      ecoDomain: "Process" as const,
      masteryTopics: ["Process — Quality Management"],
    },
    {
      id: "global_communication",
      title: "Communication Breakdown",
      description: "Ineffective communication across teams leads to rework, delays, and misunderstandings.",
      industry: "Global",
      category: "organizational" as const,
      probability: "medium" as const,
      impact: "medium" as const,
      urgency: "medium" as const,
      phase: ["Execution", "Monitoring"],
      responseOptions: [
        {
          id: "comm_1",
          title: "Establish communication plan",
          description: "Define channels, frequency, and formats for communication.",
          effectiveness: "mitigate" as const,
          estimatedCost: "low" as const,
        },
      ],
      recommendedConsiderations: [
        "Use multiple communication channels.",
        "Document decisions and rationale.",
        "Hold regular syncs across teams.",
      ],
      immediateMetricEffects: { morale: -5 },
      pmbokDomain: "Communications Management",
      pmbokPrinciple: "Manage stakeholder engagement",
      ecoDomain: "People" as const,
      masteryTopics: ["People — Communication"],
    },
  ] as RiskCatalogEntry[],

  conflicts: [
    {
      id: "global_speed_vs_quality",
      title: "Speed vs. Quality Tension",
      description: "Competing priorities between delivering quickly and maintaining high quality standards.",
      industry: "Global",
      conflictType: "values" as const,
      parties: ["Product Manager", "Engineering Lead"],
      rootCause: "Different success metrics and risk tolerance.",
      phase: ["Execution", "Monitoring"],
      availableTechniques: [
        {
          id: "tech_1",
          name: "Define quality thresholds",
          description: "Establish minimum quality standards that must not be compromised.",
          effectiveness: "good" as const,
          timeToResolve: "days" as const,
        },
        {
          id: "tech_2",
          name: "Phased release approach",
          description: "Release in phases, starting with core features at high quality.",
          effectiveness: "excellent" as const,
          timeToResolve: "weeks" as const,
        },
      ],
      likelyConsequences: [
        "Technical debt accumulation",
        "Quality issues in production",
        "Team frustration and burnout",
      ],
      immediateMetricEffects: { quality: -10, morale: -8 },
      pmbokDomain: "Quality Management",
      pmbokPrinciple: "Focus on quality",
      ecoDomain: "Process" as const,
      masteryTopics: ["Process — Quality Management", "People — Conflict Resolution"],
    },
    {
      id: "global_cost_vs_scope",
      title: "Budget vs. Scope Conflict",
      description: "Finance wants lower costs while Product wants more features and resources.",
      industry: "Global",
      conflictType: "resource" as const,
      parties: ["Finance", "Product Manager"],
      rootCause: "Limited budget cannot accommodate all desired scope.",
      phase: ["Planning", "Execution"],
      availableTechniques: [
        {
          id: "tech_1",
          name: "Prioritization exercise",
          description: "Use MoSCoW or value-based prioritization to rank features.",
          effectiveness: "good" as const,
          timeToResolve: "days" as const,
        },
        {
          id: "tech_2",
          name: "Phase the release",
          description: "Deliver core features in Phase 1, enhancements later.",
          effectiveness: "excellent" as const,
          timeToResolve: "weeks" as const,
        },
      ],
      likelyConsequences: [
        "Scope reduction",
        "Timeline extension",
        "Stakeholder dissatisfaction",
      ],
      immediateMetricEffects: { satisfaction: -12, budget: 5 },
      pmbokDomain: "Scope Management",
      pmbokPrinciple: "Steer the project",
      ecoDomain: "Business Environment" as const,
      masteryTopics: ["People — Stakeholder Engagement", "Process — Scope Management"],
    },
    {
      id: "global_process_vs_people",
      title: "Process Compliance vs. Autonomy",
      description: "Teams feel micromanaged by rigid processes; governance wants consistency.",
      industry: "Global",
      conflictType: "organizational" as const,
      parties: ["Project Manager", "Team Leads"],
      rootCause: "Misalignment on control and accountability.",
      phase: ["Execution"],
      availableTechniques: [
        {
          id: "tech_1",
          name: "Tailored process model",
          description: "Adapt processes to team maturity and project context.",
          effectiveness: "excellent" as const,
          timeToResolve: "weeks" as const,
        },
      ],
      likelyConsequences: [
        "Low team morale",
        "Higher turnover",
        "Reduced productivity",
      ],
      immediateMetricEffects: { morale: -15 },
      pmbokDomain: "Resource Management",
      pmbokPrinciple: "Manage stakeholder engagement",
      ecoDomain: "People" as const,
      masteryTopics: ["People — Emotional Intelligence", "Process — Process Improvement"],
    },
  ] as ConflictCatalogEntry[],
};
