// 15 industry business cases the learner can pick from before starting a
// simulation. Each case reframes the "opening" scenario (business case) so the
// same PMI decision engine can be replayed across many industries.

export type IndustryCase = {
  id: string;
  industry: string;
  emoji: string;
  projectName: string;
  sponsor: string;
  budget: string;   // e.g. "$120M"
  duration: string; // e.g. "24 months"
  summary: string;  // shown in the picker card
  body: string;     // replaces BUSINESS_CASE.body when this industry is selected
  challenges: string[]; // 2-3 top delivery risks (shown as chips)
};

export const INDUSTRY_CASES: IndustryCase[] = [
  {
    id: "semiconductor",
    industry: "Semiconductor",
    emoji: "🔬",
    projectName: "3nm Fab Line Expansion",
    sponsor: "VP of Manufacturing Operations",
    budget: "$1.4B",
    duration: "36 months",
    summary: "Bring a new 3nm wafer line online at an existing fabrication facility.",
    body: "The board has approved capital for a new 3nm wafer line at Fab-4. Estimated CapEx is $1.4B over 36 months. Yield targets, tool-vendor lead times (18 months on EUV), and cleanroom construction are all on the critical path. Geopolitical export controls could shift the customer mix. What is your recommendation before committing?",
    challenges: ["18-mo tool lead times", "Cleanroom yield ramp", "Export-control risk"],
  },
  {
    id: "automotive",
    industry: "Automotive",
    emoji: "🚗",
    projectName: "EV Platform Launch",
    sponsor: "Chief Product Officer",
    budget: "$680M",
    duration: "30 months",
    summary: "Design, homologate, and launch a next-generation EV vehicle platform.",
    body: "You've been named PM for a new mid-size EV platform. Budget is $680M over 30 months, with SOP (Start of Production) tied to a public reveal in Q4 next year. Battery supply, ADAS software integration, and NHTSA/UN homologation are your biggest unknowns. What is your recommendation before committing?",
    challenges: ["Battery cell supply", "ADAS software integration", "Global homologation"],
  },
  {
    id: "aviation",
    industry: "Aviation",
    emoji: "✈️",
    projectName: "Narrow-Body Avionics Refresh",
    sponsor: "Head of Fleet Engineering",
    budget: "$220M",
    duration: "24 months",
    summary: "Retrofit a 120-aircraft narrow-body fleet with a new avionics suite.",
    body: "The airline plans to retrofit 120 narrow-body aircraft with a modernized avionics suite. Budget is $220M over 24 months. Retrofits must fit inside scheduled C-checks with zero unscheduled AOG (aircraft on ground) events. FAA STC approval is required before first install. What is your recommendation before committing?",
    challenges: ["FAA STC approval", "C-check slot alignment", "Zero AOG target"],
  },
  {
    id: "supply-chain",
    industry: "Supply Chain",
    emoji: "🚚",
    projectName: "Regional DC Network Rebuild",
    sponsor: "COO",
    budget: "$95M",
    duration: "18 months",
    summary: "Redesign distribution-center network across 3 regions after nearshoring.",
    body: "Nearshoring has shifted volumes. You need to redesign a 12-DC network into 8 larger regional hubs across 3 countries. Budget is $95M over 18 months. Peak season cannot be disrupted; carrier contracts and WMS cutover risk are your top concerns. What is your recommendation before committing?",
    challenges: ["Peak-season cutover", "WMS migration", "Cross-border tariffs"],
  },
  {
    id: "engineering",
    industry: "Engineering Services",
    emoji: "🛠️",
    projectName: "Offshore Wind Substation EPC",
    sponsor: "Program Director, Renewables",
    budget: "$310M",
    duration: "28 months",
    summary: "Engineer, procure, and commission an offshore wind substation.",
    body: "An EPC contract for a 1 GW offshore wind substation has landed on your desk. Value is $310M over 28 months. Weather windows for offshore installation are narrow; long-lead HV transformers dominate the schedule. Client LDs are severe. What is your recommendation before committing?",
    challenges: ["Weather windows", "Long-lead transformers", "Liquidated damages"],
  },
  {
    id: "construction",
    industry: "Construction",
    emoji: "🏗️",
    projectName: "Downtown Mixed-Use Tower",
    sponsor: "Development Partner",
    budget: "$540M",
    duration: "32 months",
    summary: "Build a 42-story mixed-use tower on a constrained urban site.",
    body: "A 42-story mixed-use tower on a constrained downtown lot has been greenlit. Budget is $540M over 32 months. Utility relocations, adjacent-owner easements, and a fixed retail delivery date drive the schedule. What is your recommendation before committing?",
    challenges: ["Utility relocations", "Neighbor easements", "Fixed retail opening"],
  },
  {
    id: "software",
    industry: "Software / SaaS",
    emoji: "💻",
    projectName: "Customer Portal Replacement",
    sponsor: "CTO",
    budget: "$2.4M",
    duration: "9 months",
    summary: "Replace a legacy customer portal with a modern SaaS platform.",
    body: "Executive leadership has handed you a draft business case for a customer-portal replacement. Estimated cost is $2.4M over 9 months, expected NPV is $6M over 3 years, and the project aligns with corporate strategy — but market conditions are shifting. What is your recommendation before committing?",
    challenges: ["Legacy data migration", "SSO integration", "Shifting market"],
  },
  {
    id: "healthcare",
    industry: "Healthcare",
    emoji: "🏥",
    projectName: "EHR Consolidation Program",
    sponsor: "CMIO",
    budget: "$78M",
    duration: "20 months",
    summary: "Consolidate three regional EHR systems into a single tenant.",
    body: "A hospital system needs to consolidate three regional EHRs into one Epic tenant. Budget is $78M over 20 months. Clinician adoption, HIPAA compliance, and a strict no-downtime cutover window are the top concerns. What is your recommendation before committing?",
    challenges: ["Clinician adoption", "HIPAA compliance", "Zero-downtime cutover"],
  },
  {
    id: "pharma",
    industry: "Pharmaceutical",
    emoji: "💊",
    projectName: "Oncology Drug Phase III Trial",
    sponsor: "SVP Clinical Development",
    budget: "$180M",
    duration: "36 months",
    summary: "Run a global Phase III oncology trial across 220 sites.",
    body: "A pivotal Phase III oncology trial across 220 sites in 18 countries has been approved. Budget is $180M over 36 months. Patient enrollment, GCP compliance across regions, and CRO oversight are your headline risks. What is your recommendation before committing?",
    challenges: ["Enrollment velocity", "Global GCP compliance", "CRO oversight"],
  },
  {
    id: "energy",
    industry: "Energy / Oil & Gas",
    emoji: "⛽",
    projectName: "LNG Terminal Retrofit",
    sponsor: "VP Downstream",
    budget: "$820M",
    duration: "26 months",
    summary: "Retrofit an existing LNG import terminal for bi-directional export.",
    body: "You must retrofit an LNG import terminal to enable bi-directional (import + export) operation. Budget is $820M over 26 months. Regulatory permitting (FERC / DOE), turnaround planning around continued operations, and long-lead cryogenic pumps drive the plan. What is your recommendation before committing?",
    challenges: ["Regulatory permitting", "Live-plant turnaround", "Cryogenic long-leads"],
  },
  {
    id: "banking",
    industry: "Banking / FinTech",
    emoji: "🏦",
    projectName: "Core Banking Modernization",
    sponsor: "Chief Digital Officer",
    budget: "$140M",
    duration: "24 months",
    summary: "Replace a 30-year-old core banking platform with a cloud-native core.",
    body: "The bank has approved a $140M, 24-month program to replace a 30-year-old core with a cloud-native core-banking platform. Regulator concurrence, real-time payment cutover, and data reconciliation across 12M accounts are the biggest unknowns. What is your recommendation before committing?",
    challenges: ["Regulator concurrence", "Real-time payments cutover", "12M-account reconciliation"],
  },
  {
    id: "aerospace",
    industry: "Aerospace & Defense",
    emoji: "🛰️",
    projectName: "LEO Satellite Constellation",
    sponsor: "Program Executive",
    budget: "$1.1B",
    duration: "48 months",
    summary: "Design, launch, and operate a 96-satellite LEO constellation.",
    body: "A 96-satellite LEO constellation program has been funded at $1.1B over 48 months. Launch cadence, ITAR export control, orbital-debris coordination, and ground-station rollout are your critical constraints. What is your recommendation before committing?",
    challenges: ["ITAR export controls", "Launch cadence", "Ground-station rollout"],
  },
  {
    id: "manufacturing",
    industry: "Discrete Manufacturing",
    emoji: "🏭",
    projectName: "Smart Factory Rollout",
    sponsor: "VP Operations",
    budget: "$62M",
    duration: "18 months",
    summary: "Deploy MES, IIoT, and predictive maintenance across 6 plants.",
    body: "You will roll out a smart-factory stack (MES + IIoT + predictive maintenance) across 6 plants. Budget is $62M over 18 months. Union labor concerns, OT/IT security boundary, and legacy PLC integration are your top exposures. What is your recommendation before committing?",
    challenges: ["Union engagement", "OT/IT security", "Legacy PLC integration"],
  },
  {
    id: "retail",
    industry: "Retail / eCommerce",
    emoji: "🛍️",
    projectName: "Unified Commerce Platform",
    sponsor: "Chief Digital Officer",
    budget: "$45M",
    duration: "14 months",
    summary: "Unify in-store POS and online commerce onto a single platform.",
    body: "Leadership has approved a $45M, 14-month program to unify 480-store POS with the eCommerce platform. Peak-season blackout, tax-engine migration, and loyalty data merge are the top risks. What is your recommendation before committing?",
    challenges: ["Peak-season blackout", "Tax-engine migration", "Loyalty data merge"],
  },
  {
    id: "gov",
    industry: "Public Sector / Gov Tech",
    emoji: "🏛️",
    projectName: "Statewide Benefits Modernization",
    sponsor: "State CIO",
    budget: "$210M",
    duration: "30 months",
    summary: "Modernize a statewide benefits eligibility & payments system.",
    body: "The state has awarded a $210M, 30-month program to modernize benefits eligibility and payments used by 3M residents. Federal certification, accessibility (WCAG 2.2 AA), and a hard fiscal-year cutover define the plan. What is your recommendation before committing?",
    challenges: ["Federal certification", "WCAG 2.2 AA", "Fiscal-year cutover"],
  },
];

export const DEFAULT_INDUSTRY_ID = "software";

export function getIndustry(id: string | null | undefined): IndustryCase {
  return INDUSTRY_CASES.find((c) => c.id === id) ?? INDUSTRY_CASES.find((c) => c.id === DEFAULT_INDUSTRY_ID)!;
}
