// Bridges legacy INDUSTRY_CASES into the sim engine and adds per-industry
// stakeholders + recommended delivery approach. Kept thin on purpose — deeper
// case content is generated by the generator based on this metadata.

import { INDUSTRY_CASES, getIndustry } from "@/lib/sim/legacy/industries";
import { customerPortalStakeholders } from "./casepacks/customer-portal";
import type { DeliveryApproach, IndustryCaseRef, Stakeholder } from "./types";


const APPROACH_BY_ID: Record<string, DeliveryApproach> = {
  semiconductor: "Predictive",
  automotive: "Hybrid",
  aviation: "Predictive",
  "supply-chain": "Hybrid",
  engineering: "Predictive",
  construction: "Predictive",
  software: "Agile",
  healthcare: "Hybrid",
  pharma: "Predictive",
  energy: "Predictive",
  banking: "Hybrid",
  aerospace: "Hybrid",
  manufacturing: "Hybrid",
  retail: "Agile",
  gov: "Hybrid",
};

export function getCaseRef(caseId: string): IndustryCaseRef {
  const c = getIndustry(caseId);
  return { ...c, recommendedApproach: APPROACH_BY_ID[c.id] ?? "Hybrid" };
}

export function listCases(): IndustryCaseRef[] {
  return INDUSTRY_CASES.map((c) => ({
    ...c,
    recommendedApproach: APPROACH_BY_ID[c.id] ?? "Hybrid",
  }));
}

// Base stakeholder archetypes present on every project.
const BASE_STAKES: Stakeholder[] = [
  {
    id: "sponsor",
    name: "Elena Voss",
    role: "Executive Sponsor",
    personality:
      "Decisive, ROI-focused, allergic to surprises. Wants weekly one-page executive summaries and clear go/no-go recommendations.",
    priorities: ["Business value", "Risk visibility", "Governance"],
    avatarInitial: "E",
    color: "bg-indigo-500",
  },
  {
    id: "customer",
    name: "Marcus Reid",
    role: "Primary Customer",
    personality:
      "Pragmatic operator. Cares about zero-disruption cutover, training, and predictable delivery windows.",
    priorities: ["User experience", "Reliability", "Predictable go-live"],
    avatarInitial: "M",
    color: "bg-emerald-500",
  },
  {
    id: "vendor",
    name: "Priya Anand",
    role: "Vendor Program Manager",
    personality:
      "Contract-driven, will optimize for scope-of-work compliance. Escalates change requests aggressively.",
    priorities: ["Contract scope", "Change orders", "Milestones"],
    avatarInitial: "P",
    color: "bg-amber-500",
  },
  {
    id: "team-lead",
    name: "Jordan Blake",
    role: "Delivery Lead",
    personality:
      "Servant-leader engineer. Protects team focus, honest about capacity, hates command-and-control.",
    priorities: ["Team focus", "Sustainable pace", "Technical excellence"],
    avatarInitial: "J",
    color: "bg-sky-500",
  },
  {
    id: "risk-officer",
    name: "Dr. Amina Osei",
    role: "Risk & Compliance",
    personality:
      "Meticulous, quotes regulation verbatim. Wants a living register with owners and mitigation dates.",
    priorities: ["Compliance", "Auditability", "Documented mitigation"],
    avatarInitial: "A",
    color: "bg-rose-500",
  },
];

// Industry-specific role tweaks — override role/priority text only.
const ROLE_OVERRIDES: Record<string, Partial<Record<string, Partial<Stakeholder>>>> = {
  aviation: { "risk-officer": { role: "FAA Liaison", priorities: ["STC approval", "Airworthiness", "C-check alignment"] } },
  pharma: { "risk-officer": { role: "GCP / Regulatory Lead", priorities: ["GCP compliance", "IRB", "Data integrity"] } },
  banking: { "risk-officer": { role: "Chief Risk Officer", priorities: ["Regulator concurrence", "SOX", "Reconciliation"] } },
  healthcare: { "risk-officer": { role: "HIPAA / CMIO Delegate", priorities: ["HIPAA", "Clinician safety", "Downtime"] } },
  gov: { "risk-officer": { role: "Federal Certification Lead", priorities: ["MECT/CMS certification", "WCAG 2.2", "Auditability"] } },
  aerospace: { "risk-officer": { role: "ITAR / Export Control", priorities: ["ITAR", "Debris coordination", "Launch licensing"] } },
  construction: { "vendor": { role: "General Contractor", priorities: ["Trade sequencing", "Change orders", "Weather"] } },
  energy: { "risk-officer": { role: "FERC / DOE Liaison", priorities: ["FERC/DOE permits", "HSE", "Turnaround safety"] } },
};

export function stakeholdersFor(caseId: string): Stakeholder[] {
  if (caseId === "software") {
    // Customer Portal case ships with a full cross-functional cast.
    // Import lazily to avoid a circular import with the generator.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { customerPortalStakeholders } = require("./casepacks/customer-portal") as typeof import("./casepacks/customer-portal");
    return customerPortalStakeholders;
  }
  const overrides = ROLE_OVERRIDES[caseId] ?? {};
  return BASE_STAKES.map((s) => ({ ...s, ...(overrides[s.id] ?? {}) }));
}

