/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'

const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/_authenticated/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/play': typeof AuthenticatedPlayRoute
  '/api/coach': typeof ApiCoachRoute
}
export interface FileRoutesByTo {
  '/play': typeof AuthenticatedPlayRoute
  '/api/coach': typeof ApiCoachRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/play': typeof AuthenticatedPlayRoute
  '/api/coach': typeof ApiCoachRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/play' | '/api/coach'
  fileRoutesByTo: FileRoutesByTo
  to: '/play' | '/api/coach'
  id: '__root__' | '/_authenticated/play' | '/api/coach'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRoute
  ApiCoachRoute: typeof ApiCoachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedPlayRoute: AuthenticatedPlayRoute,
  ApiCoachRoute: ApiCoachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
