/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiSimStakeholderRouteImport } from './routes/api/sim-stakeholder'
import { Route as ApiMayaAskRouteImport } from './routes/api/maya-ask'
import { Route as ApiExamCoachRouteImport } from './routes/api/exam-coach'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedExamIndexRouteImport } from './routes/_authenticated/exam.index'
import { Route as AuthenticatedSimCaseIdRouteImport } from './routes/_authenticated/sim.$caseId'
import { Route as AuthenticatedExamSessionRouteImport } from './routes/_authenticated/exam.session'
import { Route as AuthenticatedExamHistoryRouteImport } from './routes/_authenticated/exam.history'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedExamReportReportIdRouteImport } from './routes/_authenticated/exam.report.$reportId'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimStakeholderRoute = ApiSimStakeholderRouteImport.update({
  id: '/api/sim-stakeholder',
  path: '/api/sim-stakeholder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMayaAskRoute = ApiMayaAskRouteImport.update({
  id: '/api/maya-ask',
  path: '/api/maya-ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExamCoachRoute = ApiExamCoachRouteImport.update({
  id: '/api/exam-coach',
  path: '/api/exam-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamIndexRoute = AuthenticatedExamIndexRouteImport.update({
  id: '/exam/',
  path: '/exam/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimCaseIdRoute = AuthenticatedSimCaseIdRouteImport.update({
  id: '/sim/$caseId',
  path: '/sim/$caseId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamSessionRoute =
  AuthenticatedExamSessionRouteImport.update({
    id: '/exam/session',
    path: '/exam/session',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamHistoryRoute =
  AuthenticatedExamHistoryRouteImport.update({
    id: '/exam/history',
    path: '/exam/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedExamReportReportIdRoute =
  AuthenticatedExamReportReportIdRouteImport.update({
    id: '/exam/report/$reportId',
    path: '/exam/report/$reportId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/play': typeof AuthenticatedPlayRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/exam-coach': typeof ApiExamCoachRoute
  '/api/maya-ask': typeof ApiMayaAskRoute
  '/api/sim-stakeholder': typeof ApiSimStakeholderRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/exam/history': typeof AuthenticatedExamHistoryRoute
  '/exam/session': typeof AuthenticatedExamSessionRoute
  '/sim/$caseId': typeof AuthenticatedSimCaseIdRoute
  '/exam/': typeof AuthenticatedExamIndexRoute
  '/exam/report/$reportId': typeof AuthenticatedExamReportReportIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/play': typeof AuthenticatedPlayRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/exam-coach': typeof ApiExamCoachRoute
  '/api/maya-ask': typeof ApiMayaAskRoute
  '/api/sim-stakeholder': typeof ApiSimStakeholderRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/exam/history': typeof AuthenticatedExamHistoryRoute
  '/exam/session': typeof AuthenticatedExamSessionRoute
  '/sim/$caseId': typeof AuthenticatedSimCaseIdRoute
  '/exam': typeof AuthenticatedExamIndexRoute
  '/exam/report/$reportId': typeof AuthenticatedExamReportReportIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/play': typeof AuthenticatedPlayRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/exam-coach': typeof ApiExamCoachRoute
  '/api/maya-ask': typeof ApiMayaAskRoute
  '/api/sim-stakeholder': typeof ApiSimStakeholderRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/_authenticated/exam/history': typeof AuthenticatedExamHistoryRoute
  '/_authenticated/exam/session': typeof AuthenticatedExamSessionRoute
  '/_authenticated/sim/$caseId': typeof AuthenticatedSimCaseIdRoute
  '/_authenticated/exam/': typeof AuthenticatedExamIndexRoute
  '/_authenticated/exam/report/$reportId': typeof AuthenticatedExamReportReportIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/analytics'
    | '/performance'
    | '/play'
    | '/api/coach'
    | '/api/exam-coach'
    | '/api/maya-ask'
    | '/api/sim-stakeholder'
    | '/checkout/return'
    | '/exam/history'
    | '/exam/session'
    | '/sim/$caseId'
    | '/exam/'
    | '/exam/report/$reportId'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/analytics'
    | '/performance'
    | '/play'
    | '/api/coach'
    | '/api/exam-coach'
    | '/api/maya-ask'
    | '/api/sim-stakeholder'
    | '/checkout/return'
    | '/exam/history'
    | '/exam/session'
    | '/sim/$caseId'
    | '/exam'
    | '/exam/report/$reportId'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/_authenticated/analytics'
    | '/_authenticated/performance'
    | '/_authenticated/play'
    | '/api/coach'
    | '/api/exam-coach'
    | '/api/maya-ask'
    | '/api/sim-stakeholder'
    | '/checkout/return'
    | '/_authenticated/exam/history'
    | '/_authenticated/exam/session'
    | '/_authenticated/sim/$caseId'
    | '/_authenticated/exam/'
    | '/_authenticated/exam/report/$reportId'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  ApiCoachRoute: typeof ApiCoachRoute
  ApiExamCoachRoute: typeof ApiExamCoachRoute
  ApiMayaAskRoute: typeof ApiMayaAskRoute
  ApiSimStakeholderRoute: typeof ApiSimStakeholderRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sim-stakeholder': {
      id: '/api/sim-stakeholder'
      path: '/api/sim-stakeholder'
      fullPath: '/api/sim-stakeholder'
      preLoaderRoute: typeof ApiSimStakeholderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maya-ask': {
      id: '/api/maya-ask'
      path: '/api/maya-ask'
      fullPath: '/api/maya-ask'
      preLoaderRoute: typeof ApiMayaAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exam-coach': {
      id: '/api/exam-coach'
      path: '/api/exam-coach'
      fullPath: '/api/exam-coach'
      preLoaderRoute: typeof ApiExamCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam/': {
      id: '/_authenticated/exam/'
      path: '/exam'
      fullPath: '/exam/'
      preLoaderRoute: typeof AuthenticatedExamIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sim/$caseId': {
      id: '/_authenticated/sim/$caseId'
      path: '/sim/$caseId'
      fullPath: '/sim/$caseId'
      preLoaderRoute: typeof AuthenticatedSimCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam/session': {
      id: '/_authenticated/exam/session'
      path: '/exam/session'
      fullPath: '/exam/session'
      preLoaderRoute: typeof AuthenticatedExamSessionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam/history': {
      id: '/_authenticated/exam/history'
      path: '/exam/history'
      fullPath: '/exam/history'
      preLoaderRoute: typeof AuthenticatedExamHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/exam/report/$reportId': {
      id: '/_authenticated/exam/report/$reportId'
      path: '/exam/report/$reportId'
      fullPath: '/exam/report/$reportId'
      preLoaderRoute: typeof AuthenticatedExamReportReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRoute
  AuthenticatedExamHistoryRoute: typeof AuthenticatedExamHistoryRoute
  AuthenticatedExamSessionRoute: typeof AuthenticatedExamSessionRoute
  AuthenticatedSimCaseIdRoute: typeof AuthenticatedSimCaseIdRoute
  AuthenticatedExamIndexRoute: typeof AuthenticatedExamIndexRoute
  AuthenticatedExamReportReportIdRoute: typeof AuthenticatedExamReportReportIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedPlayRoute: AuthenticatedPlayRoute,
  AuthenticatedExamHistoryRoute: AuthenticatedExamHistoryRoute,
  AuthenticatedExamSessionRoute: AuthenticatedExamSessionRoute,
  AuthenticatedSimCaseIdRoute: AuthenticatedSimCaseIdRoute,
  AuthenticatedExamIndexRoute: AuthenticatedExamIndexRoute,
  AuthenticatedExamReportReportIdRoute: AuthenticatedExamReportReportIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  ApiCoachRoute: ApiCoachRoute,
  ApiExamCoachRoute: ApiExamCoachRoute,
  ApiMayaAskRoute: ApiMayaAskRoute,
  ApiSimStakeholderRoute: ApiSimStakeholderRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
